Develop
gvterechov/HowItWorks pull request #1
Opened 2021-04-22 20:34 UTC by den1s0v

Диаграмма рисуется на algorithms/tasks/beta/*,
Старая view algorithms/tasks/* выглядит по-старому.

При переключении языка диаграмма ломается (см. консоль браузера после переключения и 1+ шага решения)

2021-04-22 21:30 UTC, den1s0v commented
Мои скрипты подключаются в app\views\algorithms\show_task_beta.html.erb:37-40, -- в самом "верхнем" файле из тех, где известно, что они нужны.

2021-04-23 10:02 UTC, gvterechov requested changes

2021-04-23 10:02 UTC, gvterechov commented on app/controllers/algorithms/algorithms_controller.rb
>          format.json { render json: { task_path: "/tasks/#{task.token}" }, status: :created }
вот это теперь нужно закомментить

2021-04-23 10:02 UTC, gvterechov commented on app/controllers/algorithms/algorithms_controller.rb
> +        # #{I18n.locale}/
закомментированный код стоит удалить (если это не код, который скоро вернем)

2021-04-23 10:02 UTC, gvterechov commented on app/controllers/algorithms/algorithms_controller.rb
>    def check_expression
предлагаю сделать `check_expression_beta` чтобы не терять код существующего экшена, либо параметризовать текущий экшен `check_expression`, чтобы он мог обрабатывать как для текущей страницы алгоритма, так и для beta-версии

2021-04-23 10:02 UTC, gvterechov commented on app/views/algorithms/common/_algorithm_style.html.erb
> +	#myCanvas{
идентификаторы используются для js, а классы для css - можно ли здесь заменить идентификаторы на классы?

2021-04-23 10:02 UTC, gvterechov commented on app/views/algorithms/show_task/_algorithm_diagram_field.html.erb
> +<!-- _algorithm_diagram_field.html.erb -->
этот файл точно нужен?

2021-04-23 10:02 UTC, gvterechov commented on app/views/algorithms/show_task/_algorithm_trainer.html.erb
> +<% if not hide_trace %>
- `not` стоит заменить на `!`, однако `if !` стоит заменить на `unless`
- либо можно параметр сделать как `show_trace`

2021-04-23 10:02 UTC, gvterechov commented on app/views/algorithms/show_task/_algorithm_trainer_beta.html.erb
> +  <table id=myTableAlgLeftDiagramRight>
```suggestion
  <table id="myTableAlgLeftDiagramRight">
```

2021-04-23 10:02 UTC, gvterechov commented on app/views/algorithms/show_task/_algorithm_trainer_beta.html.erb
> +  <table id=myTableAlgLeftDiagramRight>
- не очень хорошее название для `id`, лучше что-то типо table_with_diagram
- все значения атрибутов в проекте написаны snake case, а не camelcase

2021-04-23 10:02 UTC, gvterechov commented on app/views/algorithms/show_task/_algorithm_trainer_beta.html.erb
> +             hide_trace: (not ((defined?(hide_trace)) && hide_trace))
- `(not ((defined?(hide_trace)) && hide_trace))` - подобных выражений в разметке стоит избегать, разметка должна быть в декларативном стиле по возможности
- если боимся что параметр не будет передан и параметру нужно задать значение по-умолчанию, можно использовать "hide_trace ||= false". Обычно не заморачиваются по поводу `defined?(hide_trace)` если параметр обязательный, код все равно не запустится при отсутствии параметра

2021-04-23 10:02 UTC, gvterechov commented on app/views/algorithms/show_task/_algorithm_trainer_beta.html.erb
> +	<%= render partial: '/algorithms/show_task/algorithm_diagram_field'%>
```suggestion
	  <%= render partial: '/algorithms/show_task/algorithm_diagram_field'%>
```

2021-04-23 10:02 UTC, gvterechov commented on app/views/algorithms/show_task_beta.html.erb
> +<script>
код лучше не дублировать, а вынести в текущей ситуации в партиал и подключить сюда и там, где есть его копия

2021-04-23 12:14 UTC, den1s0v commented on app/controllers/algorithms/algorithms_controller.rb
>          format.json { render json: { task_path: "/tasks/#{task.token}" }, status: :created }
да, я это уже вернул как было :)

2021-04-23 12:19 UTC, den1s0v commented on app/views/algorithms/common/_algorithm_style.html.erb
> +	#myCanvas{
Можно, но есть ли смысл вводить целый класс для единственного элемента? 
Если так принято, то без проблем.

2021-04-23 12:20 UTC, den1s0v commented on app/views/algorithms/show_task/_algorithm_diagram_field.html.erb
> +<!-- _algorithm_diagram_field.html.erb -->
да, забавно получилсь)

2021-04-23 12:25 UTC, den1s0v commented on app/views/algorithms/show_task/_algorithm_trainer.html.erb
> +<% if not hide_trace %>
Поясню свой выбор: `show_trace` не подходит, т.к. я хочу показать трассу при отсутствии этого аргумента (`hide_trace=false` при этом звучит лучше)

2021-04-23 14:21 UTC, den1s0v commented on app/views/algorithms/show_task/_algorithm_trainer_beta.html.erb
> +  <table id=myTableAlgLeftDiagramRight>
Исправил

2021-04-23 14:49 UTC, den1s0v commented on app/views/algorithms/show_task_beta.html.erb
> +<script>
Сделано.

2021-04-23 14:50 UTC, den1s0v commented
Добавил 4-ый коммит, решающий большинство замечаний.

2021-04-23 22:19 UTC, gvterechov requested changes

2021-04-23 22:19 UTC, gvterechov commented on app/controllers/algorithms/algorithms_controller.rb
> +                 task_lang: params[:task_lang],
```suggestion
                 task_lang: params[:task_lang]
```

2021-04-23 22:19 UTC, gvterechov commented on app/views/algorithms/common/_algorithm_style.html.erb
> +	#paper_canvas{
можно ли здесь заменить идентификатор на класс?

2021-04-23 22:19 UTC, gvterechov commented on app/views/algorithms/common/_algorithm_style.html.erb
> +		position:absolute; /* change */
```suggestion
		z-index: -1000;
		/*width: 100%;*/
		/*height: 100%;*/
		width: 2000px;  /* Нужно константно задать ширину, не меньшую, чем размер окна - но как её получить/сюда вписать? Нельзя, чтобы Canvas растягивался при масштабировании окна (чтобы изберать искажений изображения на нём). */
		height: 600px;
		position: absolute; /* change */
```

2021-04-23 22:19 UTC, gvterechov commented on app/views/algorithms/show_task/_algorithm_trainer.html.erb
> +	<%= render partial: 'algorithms/common/trace_field', locals: { data: data } %>
```suggestion
  <%= render partial: 'algorithms/common/trace_field', locals: { data: data } %>
```

2021-04-23 22:19 UTC, gvterechov commented on app/views/algorithms/show_task/_algorithm_trainer_beta.html.erb
> +    <tr>
в фалах исходного кода следует использовать пробелы, а не табуляции

2021-04-23 22:19 UTC, gvterechov commented on app/views/algorithms/show_task/_algorithm_trainer_beta.html.erb
> +      <td id='diagram_area'>
```suggestion
      <td id="diagram_area">
```

2021-04-23 22:19 UTC, gvterechov commented on app/views/algorithms/show_task_beta.html.erb
> +    function on_solve_step(is_final) {
лишний отступ у этой строчки и ниже

2021-04-23 22:19 UTC, gvterechov commented on config/routes.rb
> +      get "/beta/tasks/:token", to: 'algorithms#show_task', defaults: {beta: true}
предлагаю удалить этот роут и оставить тот что выше

2021-04-24 12:15 UTC, gvterechov approved these changes

2021-04-24 12:15 UTC, merged