Add preview page (without diagram so far)
gvterechov/HowItWorks pull request #5
Opened 2021-06-16 00:39 UTC by den1s0v

2021-06-17 19:20 UTC, gvterechov requested changes

2021-06-17 19:20 UTC, gvterechov commented on app/controllers/algorithms/algorithms_controller.rb
> +  	unless task_token == 'preview'
стоит этот экшен контролера разделить на два

2021-06-18 20:43 UTC, den1s0v commented on app/controllers/algorithms/algorithms_controller.rb
> +  	unless task_token == 'preview'
готово

2021-06-20 16:33 UTC, gvterechov requested changes

2021-06-20 16:33 UTC, gvterechov commented on app/controllers/algorithms/algorithms_controller.rb
> +  	task_token = params[:token]
табуляция в отступе

2021-06-20 16:33 UTC, gvterechov commented on app/controllers/algorithms/algorithms_controller.rb
> +  	task_token = params[:token]
табуляция в отступе

2021-06-20 16:33 UTC, gvterechov commented on app/controllers/algorithms/algorithms_controller.rb
> +  		algorithm_as_html: 'Loading... Please wait',
Все строки на естественном языке должны находиться в языковых файлах (config/locales)

2021-06-23 20:33 UTC, gvterechov requested changes

2021-06-23 20:33 UTC, gvterechov commented on app/controllers/algorithms/algorithms_controller.rb
> +    task = AlgorithmTask.find_by(token: task_token)
```suggestion
    task = AlgorithmTask.find_by(token: params[:token])
```

2021-06-23 20:33 UTC, gvterechov commented on app/controllers/algorithms/algorithms_controller.rb
> +    task_token = params[:token]
`task_token` нигде не используется, эту строку стоит удалить

2021-06-23 20:33 UTC, gvterechov commented on app/controllers/algorithms/algorithms_controller.rb
> +          algorithm_json: result[:algorithm_json],
отступ в этой и следующей строке слишком маленький

2021-06-23 20:33 UTC, gvterechov commented on app/views/algorithms/show_task/_show_task_script.html.erb
> +	function initPreviewMode() {
слишком большой отступ

2021-06-23 20:33 UTC, gvterechov commented on app/views/algorithms/show_task/_show_task_script.html.erb
> +		if ($('#syntax_label').html() == "preview_mode") {
отступ сделан табуляциями

2021-06-23 20:33 UTC, gvterechov commented on app/views/algorithms/show_task/_show_task_script.html.erb
> +			const task_syntax = localStorage.task_syntax || "C++";
очень не хотелось бы видеть синтаксис по-умолчанию в слое представления (вот тут в js как магическую константу). предлагаю вынести куда-то в константу на сервер (в код на руби) и уже с сервера передавать в js

2021-06-23 20:33 UTC, gvterechov commented on app/views/algorithms/show_task/_show_task_script.html.erb
> +        	fix_syntax_label_text();
не совсем понял, в каком случае это полезно. можно с сервера сразу передавать нужное значение и отображать в соответствующем лейбле

2021-06-23 20:33 UTC, gvterechov commented on app/views/algorithms/common/_init_blockly_script.html.erb
> +  	$.ajax({
этот код слишком низкоуровневый для этого `if-else`, его стоит вынести в отдельную функцию, типо как `loadXML`

2021-06-23 20:33 UTC, gvterechov commented on app/views/algorithms/common/_init_blockly_script.html.erb
> +  if (!xml_text) {
можно эту ветку `if` поменять с `else` и избавиться от отрицания

2021-06-23 20:33 UTC, gvterechov commented on app/views/algorithms/common/_init_blockly_script.html.erb
> +  	  	return data.replace(/^"/, '').replace(/"$/, '');
отступ табуляцией

2021-06-23 20:33 UTC, gvterechov commented on app/views/algorithms/common/_init_blockly_script.html.erb
> +  	  	loadXML(data);
отступ табуляцией

2021-06-23 20:33 UTC, gvterechov commented on app/views/algorithms/common/_init_blockly_script.html.erb
> +  xml_text = load_xml()
очень странно что есть функция `load_xml` и `loadXML`, это может ввести в заблужение. лучше избавиться от настолько похожих названий

2021-06-23 20:33 UTC, gvterechov commented on app/views/algorithms/index.html.erb
> +    $('#enable_diagram_check').checkbox(is_beta? 'set checked' : 'set unchecked');
```suggestion
    let enable_diagram_check = $('#enable_diagram_check');
    enable_diagram_check.checkbox(is_beta? 'set checked' : 'set unchecked');
```

2021-06-23 20:33 UTC, gvterechov commented on app/views/algorithms/index.html.erb
> +    function expressionTokens(readable=false) {
нигде параметр в функцию не передается, всегда возвращается один и тот же вариант значения. возможно стоит сделать другую функцию, которая будет возвращать `Blockly.Xml.domToText`

2021-06-23 20:33 UTC, gvterechov commented on app/views/algorithms/index/_algorithm_field.html.erb
> +  <a>
замена лейбла на ссылку семантически неправильно, возможно стоит вынести чекбокс за пределы лейбла, чтобы по нажатию на лейбл и вложенных в него атрибутов чекбокс не нажимался

2021-06-23 20:33 UTC, gvterechov commented on app/views/algorithms/show_task.html.erb
> +  <% end if %>
```suggestion
  <% end %>
```

2021-06-23 20:33 UTC, gvterechov commented on app/views/algorithms/show_task/_show_task_script.html.erb
> +		const task_syntax = localStorage.task_syntax || "C++";
где-то я это уже видел...

2021-06-23 20:33 UTC, gvterechov commented on app/views/algorithms/show_task/_show_task_script.html.erb
> +		let lang = $('#lang').val();
и это тоже видел...

2021-06-23 20:33 UTC, gvterechov commented on app/views/algorithms/show_task/_show_task_script.html.erb
> +	function initPreviewMode() {
слишком большая функция, стоит декомпозировать

2021-06-23 20:33 UTC, gvterechov commented on app/views/algorithms/show_task/_show_task_script.html.erb
> +		var target = document.getElementById('algorithm_trainer').parentNode;
`var` использовать не стоит

2021-06-23 20:33 UTC, gvterechov commented on app/views/algorithms/show_task/_show_task_script.html.erb
> +	if ($('#preview_mode').val() == "true") {
это условия встречается несколько раз, возможно стоит разделить js на два отдельных - для предпросмотра и без него

2021-06-23 20:33 UTC, gvterechov commented on app/views/algorithms/show_task_beta.html.erb
> +  <% if @preview_mode %>
код дублируется, возможно стоит вынести в хелпер

2021-06-24 21:15 UTC, den1s0v commented on app/controllers/algorithms/algorithms_controller.rb
> +          algorithm_json: result[:algorithm_json],
Не понял, в чём проблема. 
"algorithm_json: ..." начинается под строкой того же уровня

2021-06-24 21:20 UTC, den1s0v commented on app/views/algorithms/show_task/_show_task_script.html.erb
> +        	fix_syntax_label_text();
Тут проблема в том, что в режиме предпросмотра сервер не знает, какой синтаксис передавать на страницу -- он извлекается из localStorage и прописывается в label. 
Чтобы передать нужный синтаксис через сервер, нужно обновить route и экшн для предпросмотра -- видимо, так и нужно было сделать (поставил в план)

2021-06-24 21:39 UTC, den1s0v commented on app/views/algorithms/index/_algorithm_field.html.erb
> +  <a>
да, я пробовал, но тогда чекбокс уходит 
на строку ниже. 
Как оставить её справа на той же строке, пока не понимаю (надо что-то в CSS прописать, но что?)

2021-07-17 17:08 UTC, closed without merging

2021-07-17 17:09 UTC, den1s0v commented
This one is outdated