Task preview page
gvterechov/HowItWorks pull request #8
Opened 2021-07-01 17:20 UTC by den1s0v

2021-07-01 20:31 UTC, gvterechov requested changes

2021-07-01 20:31 UTC, gvterechov commented on app/views/algorithms/index.html.erb
> +    $('#enable_diagram_check').checkbox({
```suggestion
    let enable_diagram_check = $('#enable_diagram_check');
    enable_diagram_check.checkbox(is_beta? 'set checked' : 'set unchecked');
    enable_diagram_check.checkbox("set enabled");
    enable_diagram_check.checkbox({
```

2021-07-01 20:31 UTC, gvterechov commented on app/views/algorithms/show_task.html.erb
> +<input type="hidden" id="task_token" value="<%= @preview_mode? 'null' : @task.token %>">
бизнес логики во вьюхе быть не должно (циклов, развилок и т.д.), данные стоит подготовить заранее (например, в контроллере)

2021-07-01 20:31 UTC, gvterechov commented on app/views/algorithms/show_task/_show_task_diagram_script.html.erb
> +        window.globals.paper_init();
отступы

2021-07-01 20:31 UTC, gvterechov commented on app/views/algorithms/show_task/_show_task_diagram_script.html.erb
> +      setTimeout(paper_on_load, 200);
очень странная конструкция. если это нужно чтобы выполнилась функция paper_on_load через 200мс, то для слабых компьютеров нужно больше задержку делать. можно все обернуть в `$(function(){...});` (`document.ready` или `window.onload`)

2021-07-01 20:31 UTC, gvterechov commented on app/views/algorithms/show_task/_show_task_script.html.erb
> +	function bindAlgorithmButtons() {
отступ

2021-07-01 20:31 UTC, gvterechov commented on app/views/algorithms/show_task/_show_task_script.html.erb
> +            if (window.on_solve_step) on_solve_step(true);
лучше сделать с фигурными скобками

2021-07-01 20:31 UTC, gvterechov commented on app/views/algorithms/show_task/_show_task_script.html.erb
> +            if (window.on_solve_step) on_solve_step(false);
лучше сделать с фигурными скобками

2021-07-01 21:35 UTC, den1s0v commented on app/views/algorithms/show_task/_show_task_diagram_script.html.erb
> +      setTimeout(paper_on_load, 200);
Это отложенно-рекурсивный вызов; ожидание подгрузки скриптов. Уже убрал это совсем.

2021-07-05 21:50 UTC, gvterechov requested changes

2021-07-05 21:50 UTC, gvterechov commented on app/views/algorithms/show_task/_show_task_script.html.erb
> +    const task_syntax = localStorage.task_syntax || "<%= t('algorithms.default_syntax') %>";
вставки ruby кода в js не стоит делать - чтобы они заработали с вебпаков, нужно добавить лоадер + это увеличит время компиляции скриптов. лучше положить нужную информацию в input type="hidden"

2021-07-05 21:50 UTC, gvterechov commented on app/views/algorithms/show_task/_show_task_script.html.erb
> +  function initPreviewMode() {
отступ

2021-07-05 21:50 UTC, gvterechov commented on app/views/algorithms/show_task_beta.html.erb
> +  <div class="ui mini blue button" <% unless @preview_mode %> style="display: none;" <% end %> id="back_to_editor"><i class="edit icon"></i> <%= t('algorithms.back_to_editor') %></div>
```suggestion
  <div class="ui mini blue button" <%= 'style="display: none;"' unless @preview_mode %> id="back_to_editor"><i class="edit icon"></i> <%= t('algorithms.back_to_editor') %></div>
```

2021-07-05 21:50 UTC, gvterechov commented on config/locales/algorithms.en.yml
> +      algorithm_loading: 'Loading... Please wait...'
предлагаю эту строку вынести в файл с общими строками - `en.yml`, т.к. будет полезно и в других инструментах

2021-07-08 19:27 UTC, gvterechov requested changes

2021-07-08 19:27 UTC, gvterechov commented on app/views/algorithms/show_task/_show_task_script.html.erb
> +    var target = document.getElementById('algorithm_trainer').parentNode;
```suggestion
    let target = document.getElementById('algorithm_trainer').parentNode;
```

2021-07-08 19:27 UTC, gvterechov commented on public/static/paper/paper-canvas.js
> +	// Create an empty project and a view for the canvas:
отступ

2021-07-08 19:27 UTC, gvterechov commented on public/static/paper/paper-canvas.js
> + 	let h = Math.max(10, (rect1.top - rect2.bottom) / 2);
отступ

2021-07-12 17:56 UTC, gvterechov requested changes

2021-07-12 17:56 UTC, gvterechov commented on app/views/algorithms/show_task.html.erb
> +  <div class="ui mini blue button" <% unless @preview_mode %> style="display: none;" <% end %> id="back_to_editor"><i class="edit icon"></i> <%= t('algorithms.back_to_editor') %></div>
```suggestion
  <div class="ui mini blue button" <% 'style="display: none;"' unless @preview_mode %> id="back_to_editor"><i class="edit icon"></i> <%= t('algorithms.back_to_editor') %></div>
```

2021-07-13 19:23 UTC, gvterechov approved these changes

2021-07-13 22:04 UTC, den1s0v commented
Добавлен предпросмотр задачи без сохранения в базу и без создания попытки

2021-07-13 22:05 UTC, merged